# Generated by Django 4.2.5 on 2023-10-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('bank_label', models.CharField(max_length=50)),
                ('account_type_label', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.PositiveIntegerField()),
                ('installment_interest', models.FloatField()),
                ('installment_value', models.FloatField()),
                ('full_value', models.FloatField()),
                ('comission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TabelaTaxas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('installments', models.ManyToManyField(to='loans.installment')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_interest', models.FloatField()),
                ('installment_interest_value', models.FloatField()),
                ('comission', models.FloatField()),
                ('comission_value', models.FloatField()),
                ('installment_value', models.FloatField()),
                ('card_number', models.CharField(max_length=16)),
                ('desired_value', models.FloatField()),
                ('total_loan', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.cliente')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.installment')),
                ('rate_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.tabelataxas')),
            ],
        ),
    ]
