# Generated by Django 4.2.5 on 2023-10-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='tabelaTaxas',
            new_name='tableTax',
        ),
    ]
