# Generated by Django 4.2.5 on 2023-10-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelataxas',
            name='installments',
        ),
        migrations.AddField(
            model_name='installment',
            name='tabela_taxas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.tabelataxas'),
        ),
    ]
