# Generated by Django 4.2.5 on 2023-10-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_tabelataxas_installments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='tabela_taxas',
        ),
        migrations.RemoveField(
            model_name='tabelataxas',
            name='name',
        ),
        migrations.AddField(
            model_name='tabelataxas',
            name='interestRates',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tabelataxas',
            name='numberInstallments',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
