# Generated by Django 4.2.5 on 2023-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_installment_tabela_taxas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelataxas',
            name='interestRates',
            field=models.FloatField(default=0),
        ),
    ]
