# Generated by Django 4.2.5 on 2023-10-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_tabelataxas_interestrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='tabelaTaxas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.tabelataxas'),
        ),
    ]
